### ISSUE TITLE
What money supply should be with $MUSIC?  Let's discuss

### ISSUE THREAD

**Issue by immartian** [Musicoin/MCIPs#1]
//This is just a general idea to foster further discussions. It is supposedly to have full MCIPs to summarize all discussion and take actions accordingly. 

Ever since $MUSIC blockchain genesis on Feb.11th, we have received several rounds of ebb and flow from miners community and eventually all reflected in market. 

![image](https://cloud.githubusercontent.com/assets/81030/26442571/aa0da638-4167-11e7-802b-4252ab8c399b.png)

The volatility was normal to any new currencies, which was also in my expectations. However, the biggest controversy in the past months, on money policy, didn't get well understood by community. Since it is related to the currency performance, the same time leading to the future of the system, I have to explain more and seek further deliberations. 

The design of $MUSIC(or Musicoin the whole project) is to peg with music consumption, or we won't even create this new currency and make it mine-able. It also means it's associated with real world economy. Music industry yield 6-7 Billion USD revenue in digital recording, which is far below the hay days in history. The issuance of a new currency for $MUSIC, seemingly not so significant, but maybe helpful to make it great again. It's the design of the currency and blockchain, and we are here already.  I explained many times that music consumption in this world is much valuable than current economic scale, but not well reflected and/or collected because of the wrecked structure of legacy system. $MUSIC is to change the paradigm, it's why a currency should match this vision. 

It's why we didn't set the cap of the issuance of the currency and let it naturally emit from the adoption. Nonetheless, I also heard the outcrying from early adopters who wish to invest and see it's up-roaring all the time(it's impossible to any currency, right?). I'm seriously thinking of how to adjust the policy in the next upgrades. Of course, it needs some systematic thinking and holistic thinking. We should keep the faith on the vision, the same considering all the stakeholders along the road.  I hope this issue will lead a constructive process to start working toward a more delicate solution in the next move, and give the system a brighter future.

**Comment by Mustard5** [comment]
I look forward to watching this discussion.

**Comment by immartian** [comment]
In the early design, we considered a lot how to keep the system neutral but ignored how to really help boost the Musiconomy with money policy. We still think the decision with no reservation, pre-mined coins, and with no ICO, is correct, which enabled miners to start the adventure equally. 

However, along the journey, we started to realize the money policy should be adjusted to be more coherent with Muisconomy which was thought as the upper layer of the whole system. E.g. If we keep a linear issuance of money like current one, there won't be benefits to early adopters. Also the musicians who join the system can't see any incentives rather than traditional system. Without significant differences, they would be reluctant to share and invite their fans, their friends to join the same movement. Thus the whole energy of the system won't be lifted up continuously. With slow adoption, early investors and miners can't realize their profit as well. It's a negative feedback loop we can solve perfectly.  

So in next step we may have to make some changes on money policy. The angles may reside on the emission rate and curve(block reward), some reservation fund for musicians, and/or some other options like Pay-Per-Play binding rules.  I will share a blog post soon on all these ideas and eventually propose to MCIPs before implementation.

**Comment by dylantarre** [comment]
There are both concerns from the investors and miners who want the price to increase. The musicians might like their holdings to increase, if they don't immediately convert them to fiat. If they believe in the platform, the only reason they would hold the coins is if they increase in value. Otherwise, they need to pay bills. Miners would not continue to mine if it is not profitable. Listeners are concerned about the increasing price of tips and plays in the pay-per-play model, so in a way they have an opposite concern, and would love the price of 1 musicoin to go down. 

One suggestion might be that tips and plays are not tied to 1 musicoin but a market rate based on fiat, let's say $0.01 per tip, or whatever the musician chooses. I am not sure this is the right solution, as it makes the whole tipping process confusing. When I tip I might give a fraction of a Musicoin It makes sense that 1 musicoin = 1 play or 1 tip. There's no getting around the simplicity of that, and it works internationally. The benefit though is that a listener would always knows the cost of a play and tip. Right now it's a guessing game, and becomes untenable in the future as the price increases.

We could adjust emission to keep it always pegged at a target rate, but this does not reward early adopers, miners, investors, and musicians who hold. Ultimately in a "Musiconomy" though, you need the economy to be stable enough to know what you're giving and know what you're getting. 

Musicians aren't investors, or usually concerned with saving, they just need to pay the bills. Those bills can't be paid in Musicoin, so most indie Musicians will not be holding, but cashing out. Therefore, it is of no concern to listeners or musicians that the price increases. To them, they would prefer a stable economy in which they know what they are getting.

**Comment by immartian** [comment]
It's why the "Universal Basic Income" is weighing in more and more into my mind recently and probably should be considered into the upcoming revision of the money policy. If we can make a reservation of fund entitled to subsidize the pay-per-play contract, we can definitely assure musicians would love to share their content more and more to the system because of assured income. Further added value can be seen as well based on this but could be 5x, 10x effect.

**Comment by vvinam** [comment]
1tip=0.1$
use MUSIC buy a tip

**Comment by thepeekay** [comment]
@immartian A universal basic income doesn't sound like a bad idea. To make sure that listeners are protected from MUSIC value increases or decreases, they price can be set in fiat by the artist so they can have a guarantee on the income and the listener on the cost. After that, it can be up to the artist if they want to hold the MC or cash it out immediately.

I think that's what @dylantarre described as well when it comes to putting a price in fiat.

**Comment by kidwok** [comment]
Sorry I'm late to the game. I think I might have a LOT of artist perspective to add here considering I have been looking into royalties and how to increase them the past 5 years.  I have found out that it IS difficult to make a go at finding the royalties to support yourself fully!  Most artists don't know how to drive traffic to their materials, and the $Music service has a whole list of brick walls to overcome to become efficient. I think about it every day, how I can become the first comic to utilize this medium the fastest and most efficient, you'll see my thoughts below my credentials. 

NO ROYALTY --- In 1999, Dragon Ball Z (Funimation) moved from Canada, a country that required royalty payouts,  to Texas, USA, a state that does NOT require royalty payouts.  I was the only voice actor to resign after a year and half after seeing that it was ONLY a $50/hr paycheck with no long-term benefits for my family.

BIGGEST ROYALTIES ON SCALE - In 2002, I began getting HEAVY rotation from XM Satellite, continued thru 2007, until the Sirius/XM merger when royalties slowed.  I found out thru former PD of XM that he was fired and told by the new head PD of comedy at Sirius during an argument, "I know you have a lot of comics that you have recorded and are getting producer royalties to and I therefore I will NEVER play ANY of the artists you played at XM here at Sirius!". This effectively cut my royalties from over $11,000 in 2006 to what it is today about $350/year.  I have attempted to get into that loop again, but I don't like to beg to get airplay, I am hope my material speaks for itself after 5 minutes.

In 2009, I got onto numerous other services thru CDBaby and Tunecore.com .  I prefer the tunecore.com model between the two.  I like the fact you can see where each one came from but that novelty quickly wears off, and now I only check my balance.  I like the auto deposit features,  deposits in bank account based on preset payout limits!  

Royalty model for Spotify was random from .004 cents to .007 per track with a play "registering" at 35 seconds, leading me to wonder why I was giving them 5 minute comedy tracks. It would be in my best interest to keep them as short as possible to reap max rewards for each track play.  I lost interest driving traffic with such LOW payouts.

In 2009, I was receiving airplay from the "Comedy 24/7" IHEARTRADIO network. CXArtist distributes this royalty along with royalties from the 2016 springing up of "Today's Comedy" radio stations popping up across the U.S. currently.  Less royalties than Sirius, way more than Spotify and Pandora. 

Youtube began putting clauses that they could deny royalties for anything with language or "questionable content" so I gave up on them.

NOW, $MUSICCOIN!  I LOVE:

1) The ability to interact with the audience!  I can see where people are listening in Tunecore, but I can have conversations with people around the world to hear THEIR thoughts!! This is priceless!!

2) Royalty at $0.01 is WAY above ALL the other services with HIGH potential for long term benefits should this model stick.

3) Tipping is neat, but took me a second to understand and all of a sudden I had tipped those who commented and tipped me on accident, thus, a WASH!

I am sorry I was late on the Musiconomi model chat.  I think that the WHOLE community could be moved under that umbrella with a TRANSPARENT proposal to the artists.  Artists have been SCREWED by 10% or MORE (up to 35% in LA after Manager & VO Agent & Talent Agent cut) throughout the industry!  I think the fact that your royalty is so high loans itself to pitching to the artist community a 2-5% "fee" for the miner and Musiconomi overhead.  This can be auto split off the coin at every upload.  Good artists are used to putting back into their art to help their long term and THIS would be easy to pitch.  Also, what about GIVING OUT $musiccoin to an advertiser as a "bonus" to their patrons?  Advertisers could "sponsor" artists' music or have their own "AT&T Jams" page with their OWN artists that they give their coins to driving traffic to their page to listen to their sponsored artists, splitting the royalty automatically!  Nerdgasm here!  Advertisers can pay out in $music for their customers watching a video or whatever that model is I see all over for "bonus diamonds" on apps (ADD here, keeps a LOT to keep me engaged).  Artists can offer people $music coin in the banner areas to listen to ONE of their tracks, thus allowing artists to create their own banners and pull in new audiences with a $/per new fan acquisition budget.

LARGEST downside of $Musiccoin:

The ONLY people I am confident giving the "invites" to are people that are fluent in Bitcoin.  Total number of artists/fans I have confidence in the fact that they will be able to navigate this easy enough to return: 0  THIS has been my MAIN problem with trying to figure out how to market myself using this service.  I wanna like it, but it's just too complicated for my non-nerd friends just yet.  I am still thinking, but the acquisition of $music takes so many steps that you REALLY gotta wanna hear the artist really bad and there has GOT to be NO OTHER EASIER access to their catalog.  Having "exclusive" tracks might, but then, only my MOST hardcore fans would dare (the ones that drive 5 hours to see me bc they know that's the closest I'll be).  Those fans are few and far between for independent artists.  Most are 6-8 on the "10" fan scale and that is the level of their effort as well.  ONLY the 10s will dare try this crypto navigation.

I hope I have added enough to get MORE brainstorming happening!  

REMEMBER: During the brainstorming sessions, there ARE NO SILLY answers or ideas!  A "dumb" idea may springboard to a "genius" one, such that it would not have been attained had there not been a springboard to reach it!

Sincerely your Ninja $Musiccoin Brother from another Ninja $Musiccoin Mother!

ChinaMan

**Comment by immartian** [comment]
@kidwok You are not late, it's the dawn of the revolution. I really love this writing and shared with my partner already.  His feedback I share here first, "Building  a music ecosystem such as the one we vision requires many brilliant minds to come together all with laser focus on crafting the most user friendly experience known to man. Only then will everyone adopt it. If we don’t do it, it will never take flight... "

There are many ideas on top layer we called "application layer", which includes UX, and many dynamic rules to fit for the climate. It can be definite team work to engage community especially early adopters to make everyone profitable and fulfilled. It's why I'm thinking to put a more sustainable model here on money policy, which will eventually impact for a decade or longer.

**Comment by DipankarJDutta** [comment]
@immartian. Thank you for all the work with the musicoin project. It's a fantastic project trying to solve a very important problem, providing fair value to both artists and users.

I feel that the monetary policy of the project should evolve so that the project itself continues to grow and push into the mainstream. And this open discussion is a very welcome initiative from the musicoin team.

The following is my 2 cents worth of opinion. I hope you will consider them for your upcoming roadmap.

**A. Fractional MCs should be assigned for pay per play (PPP) in the future, instead of whole MCs. Because of the following reasons:**

1. MC being openly traded is volatile and it is necessary to provide artists and listeners a stable currency to spend for streaming (PPP). By using fractional MCs, we can unpeg PPP from market forces.

Say 1 MC = $1 in 06/20/2020. For 06/20/2020, 1 PPP = 0.01 MC ($0.01).

And say 1 MC = $2 in 06/21/2020. For 06/21/2020, 1 PPP = 0.005 MC ($0.01).

So the PPP can be pegged to a fluctuating fractional MC which is determined (in real time) by the market price of Musicoin.

This also gives more flexibility to the artist. Say Eminem pegs his songs at 0.02MC PPP and Rihanna does it at 0.025MC PPP.

One criticism could be that it is too confusing to the user. That need not be the case. This can all be done in the backend with no confusion to the user. 

#PPPs available to user for 1MC (certain date) = Market price of  1MC on that date/$0.01 or whatever the artist decides.

2. Users of incumbent platforms like Spotify are used to buffet streaming options like $10/month. If whole MCs are used for PPP, we will cap the upper value of an MC forever (maybe closer to 1 cent or lower).

This has two disadvantages, one is obviously for holders of the coin as their investment value will depreciate.

The other is for artists, in that they may want to be paid more than 1MC for PPP in case market forces bring MC to say $0.00001. This will drastically lower the economic incentive of an artist to participate in the platform.

**B. We should cap the emission of coins at a certain point just like ethereum by implementing a difficulty bomb and switching to a version of proof of stake (proof of sharing keeps coming up in the slack)**

The simple reason is it is the surest way to raise money for the platform. Investors will come in droves, Musicoin value will rise, and assuming you have a stockpile of coins for the development of the project, this will allow you to recruit more developers, spend on advertising and all the other things you need to do to push Musicoin into the mainstream.

Thank you!

**Comment by immartian** [comment]
@dipdutta , I'm considering similar thing in upcoming milestones of $MUSIC blockhcain, actually it can be tested in the next step, if we got fully fueled.  The biggest concern is on usability. While the volatility of a cryptocurrency actually would make the pegging with fiat currency(USD in your case) difficult, it could dramatically downgrade the user experience. E.g. Imagine when the system calculate current PPP and apply to the application layer, the price could have a fluctuation already before it's been applied to consumption. It can be solved easily with traditional stack, however, it's getting complicated with blockchain stack, which I have no full confidence but welcome some successful references.

**Comment by DeadlyBuda** [comment]
I think a lot of problems can be solved by pegging a "play" to $00.01 USD and you would get an amount of MC based on the current exchange rate. This is pretty simple, I understand, but I think it has a lot of benefits.
1. Musicoin's payout would always be larger than Spotify, Pandora, etc. If not, the rate could be adjusted after a vote if needed. 
2. This introduces the users in a fun way to monetary lessons that they would benefit from learning anyway. I think one of the exciting things about any crypto is its fluctuations and it hooks people into the system in a good way. By seeing how MC fluctuates, they will question the currency of their own country and see how inflation effects them. This is a good lesson for especially the young people using the platform. 
3. A tip could also be pegged to $00.01 as well. This keeps people willing to tip and share. So instead of giving 1 or 5 MC tips, you would give 1-5 "tips" (each "tip" being worth $00.01). Perhaps it should have a different name than "tip"?
4. As people realize their MC is growing in value it encourages them to promote the platform more, their music, their friends music. The miners can collect on their investment and continue to be rewarded from processing transactions. Also, physical goods and services built around MC would benefit. For example, if a band receives 1000 MC today for a band t-shirt, and MC prices goes from .01 USD to .02 USD, then they will be able to make some actual profit after making the shirt. 
5. The $00.01 stream peg is very understandable, and easy to explain to people. This will facilitate UBI, and then eventually it will be easier to introduce them to Proof-of-Sharing. But, I truly believe we must start where people can easily understand. Perhaps there will be a bubble and crash at some point, but I think after the crash the actual infrastructure and foundation has been built. All the songs and listeners and everything else actually exists. People won't stop listening to the music. As the ecosystem stabilizes it would reach its ideal state. People are listening, sharing, and hopefully living off their creative efforts in a fairly predictable way.

**Comment by immartian** [comment]
we discussed the pros/cons of pegging with 0.01usd, which is called by community for long time. The problem is the volatility of cryptocurrency could make the whole system very messy from hour to hour when you are trying to listen/tips, because it could be a coin, or sometimes 2.7 coin, or sometimes 0.5 coins etc.
the ultimate psychological issue is people don't trust crypto, they still believe USD

**Comment by DeadlyBuda** [comment]
A couple thoughts cross my mind after I have re-read the above discussion.
1. Perhaps it is best to let the market decide how valuable a "play" is. Competitors like Soundchain are now saying they will be paying up to $2 a play!???! Perhaps we will all be surprised how valuable a MC can become if the listener doesn't have to pay for it. Perhaps in this case the difficulty bomb must be eliminated?
2. @kidwok brings up an interesting thought: Perhaps one MC = 5 minutes of play?
3. I think the market volatility of MC in the USD peg scenario would actually be a benefit under the UBI implementation. As listeners are not paying anyway they will not care. But those invested in the system will endeavor to keep the system robust and good. And the price going up and down honestly creates the same excitement as gambling, which for better or worse, people seem to like. 
4. I'm thinking perhaps worrying too much about tips is counterproductive. Users should simply be able to set a tip amount manually, whatever they feel. 
5. Regarding @dipdutta 's idea: perhaps the community could vote every month on the valuation of 1 play? For example, as the current price to USD now is about .02, maybe the community would vote that 1 play = .5 MC? The voting mechanism could be installed into the music player/wallet. Here we would see what the public really thinks music is worth! We may not like the answer is the chance we take. 
If the public consistently votes the price too high though, there should be a safeguard that will automatically lower the amount based on available supply of MC. Perhaps the music player/wallet/voter/messenger could also do low level mining as well?
6. Another thought: Maybe we should just have a new name for 100 MC? A "Watt" I think Muse is already using "Note". There could be a token that was specifically pegged to MC that was always worth 100 MC? That said, it doesn't really help the early adopters or miners though.

**Comment by DeadlyBuda** [comment]
@immartian  wrote
> So in next step we may have to make some changes on money policy. The angles may reside on the emission rate and curve(block reward), some reservation fund for musicians, and/or some other options like Pay-Per-Play binding rules. I will share a blog post soon on all these ideas and eventually propose to MCIPs before implementation.

I think now I am starting to understand this view better. Perhaps in this scenario the price of a play is automatically adjusted based on the the total available supply of MC being mined and shared in relation to the amount of user activity?

**Comment by dylantarre** [comment]
These suggestions such as pegging a play to USD, or voting on the price, and adjusting, or changing it based on time of play. For each suggestions, we need to think about the technical aspect of implementation. Some of these suggestions are massive engineering efforts, or create very hard problems to solve. Not only that but the amount of ramification or potential bugs it may have. The simpler the solution the quicker we can get to MVP and test it. 

The most foolproof things to do it seems to me are internal and affected by the chain only, not data outside of it (USD price, song length, etc). The simplicity of 1 music per play makes sense. These days I'm leaning towards the side of adjusting the supply based on transaction rate to keep it stable, instead of adjusting the price of play.  Since our streaming platform is only but one smart contract built on the chain, it's not easy for us to dictate a global play price once there are more platforms.

**Comment by immartian** [comment]
![image](https://user-images.githubusercontent.com/81030/29205392-20652728-7eaf-11e7-9e13-2e844cf65b74.png)

Along with the UBI model design and testing, we've received more inputs from community, and accumulated more ideas to make it more sustainable and useful.  As we have realized the barriers to drag the speed of growth. 

We have been thinking too much on the future scenarios about $MUSIC as a currency, actually echoed by many thoughtful supporters. However, there are some cruelties around this vision, which is not committing short-term gains for traders, and partly affecting miners as well(we can call them together investors).  What investors expect in early stage, no exceptions, is profit and the higher the happier. This exception is definitely harmful to the long term goal of this blockchain project, but also reasonable as materialism humanity. 

UBI deliberately removed the ceiling of coin value, from the harsh will of early PPP design. PPP bonding with 1MC will be changed with UBI by replacing the 1MC with an Oracle contract on top. The Oracle contract will not only store the UBI pool, but also regulate the unit payment to a PPP contract if musicians agree to follow the standard(Musicians can define their own price on streaming without UBI subsidy). In this way, almost all music can be free to end users under this scheme, which they would be applauding. Musicians, contrary to conventional view, will receive income from the "free listening" accordingly.

**Comment by ryangtanaka-org** [comment]
Had a basic question about mining after UBI -- it was said that the miners will be providing the coins to listeners for the free listens that are given to the user.  I was wondering what the miners' incentive would be in this model...what do they get in return for providing this service?  Or is the give-away just a % of the whole?

I've probably missed something somewhere but would like to know how it all comes together.

**Comment by ALB3ON** [comment]
I think for sustainability,  the Musicoin economy has to move toward hybrid approach where the coin value goes up and listeners do not have to tip after so many plays after so many tips (ex. USD 1.25 per song or some market rate).   The platform can gain value to attract bigger names from the music industry, mining incentives will be built in, and increased listener buying power.
